name: Spellcheck
on:
  pull_request:
    paths:
    - '**.md'
  schedule:
    - cron: '23 4 * * 1'

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
   
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.23.0
